# Generated by Django 5.2.7 on 2025-10-03 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_project_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='project_screenshots/'),
        ),
    ]
