# Generated by Django 5.2.6 on 2025-10-06 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_projectlike'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectlike',
            old_name='liked_at',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='projectlike',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
