# Generated by Django 5.2.7 on 2025-10-06 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_studentprofile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentfollow',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('like', 'Project Like'), ('follow', 'New Follow Request'), ('follow_accepted', 'Follow Request Accepted')], max_length=20),
        ),
    ]
