# Generated by Django 5.2.6 on 2025-10-09 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_studentfollow_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('like', 'Project Like'), ('follow', 'New Follow Request'), ('follow_accepted', 'Follow Request Accepted'), ('hire', 'Hire Request')], max_length=20),
        ),
    ]
