# Generated by Django 5.2.6 on 2025-11-04 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_recruiterprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruiterprofile',
            name='company_website',
        ),
        migrations.AddField(
            model_name='recruiterprofile',
            name='company_linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recruiterprofile',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to='company_logos/'),
        ),
    ]
