# Generated by Django 5.2.6 on 2025-11-04 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_remove_recruiterprofile_company_website_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruiterprofile',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='recruiterprofile',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved')], default='pending', help_text='Approval status of the recruiter', max_length=20),
        ),
    ]
