# Generated by Django 5.2.7 on 2025-11-04 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_remove_recruiterprofile_is_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiterprofile',
            name='hiring_process_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recruiterprofile',
            name='messages_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recruiterprofile',
            name='profile_views',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recruiterprofile',
            name='saved_students',
            field=models.ManyToManyField(blank=True, related_name='saved_by_recruiters', to='accounts.studentprofile'),
        ),
    ]
