# Generated by Django 5.2.6 on 2025-11-05 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_recruiterprofile_hiring_process_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='profile_views',
            field=models.IntegerField(default=0),
        ),
    ]
