# Generated by Django 5.2.7 on 2025-11-06 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_hiringprocess'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='hiring_process',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.hiringprocess'),
        ),
    ]
